/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundSettings: typeof import('./src/components/BackgroundSettings.vue')['default']
    CarFrame: typeof import('./src/components/car/CarFrame.vue')['default']
    ComboDevices: typeof import('./src/components/combo/ComboDevices.vue')['default']
    MacDock: typeof import('./src/components/mac/MacDock.vue')['default']
    MacFrame: typeof import('./src/components/mac/MacFrame.vue')['default']
    MacTopBar: typeof import('./src/components/mac/MacTopBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NUpload: typeof import('naive-ui')['NUpload']
    PhoneCameraIcon: typeof import('./src/components/iphone/PhoneCameraIcon.vue')['default']
    PhoneFlashlightIcon: typeof import('./src/components/iphone/PhoneFlashlightIcon.vue')['default']
    PhoneFrame: typeof import('./src/components/iphone/PhoneFrame.vue')['default']
    PhoneLockBottom: typeof import('./src/components/iphone/PhoneLockBottom.vue')['default']
    PhoneTopIcon: typeof import('./src/components/iphone/PhoneTopIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabletDock: typeof import('./src/components/ipad/TabletDock.vue')['default']
    TabletFrame: typeof import('./src/components/ipad/TabletFrame.vue')['default']
    TabletTopBar: typeof import('./src/components/ipad/TabletTopBar.vue')['default']
    WallpaperEditor: typeof import('./src/components/WallpaperEditor.vue')['default']
    WatermarkSettings: typeof import('./src/components/WatermarkSettings.vue')['default']
  }
}
