/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundSettings: typeof import('./../components/toolbar/BackgroundSettings.vue')['default']
    CarFrame: typeof import('./../components/car/CarFrame.vue')['default']
    ComboDevices: typeof import('./../components/combo/ComboDevices.vue')['default']
    CustomFrame: typeof import('./../components/custom/CustomFrame.vue')['default']
    FileUploader: typeof import('./../components/common/FileUploader.vue')['default']
    Footer: typeof import('./../components/common/Footer.vue')['default']
    Header: typeof import('./../components/common/Header.vue')['default']
    HomeIndicator: typeof import('./../components/common/HomeIndicator.vue')['default']
    MacFrame: typeof import('./../components/mac/MacFrame.vue')['default']
    MobileBottomSheet: typeof import('./../components/common/MobileBottomSheet.vue')['default']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    PersonalTemplates: typeof import('./../components/PersonalTemplates.vue')['default']
    PhoneCameraIcon: typeof import('./../components/iphone/PhoneCameraIcon.vue')['default']
    PhoneFlashlightIcon: typeof import('./../components/iphone/PhoneFlashlightIcon.vue')['default']
    PhoneFrame: typeof import('./../components/iphone/PhoneFrame.vue')['default']
    PhoneLockBottom: typeof import('./../components/iphone/PhoneLockBottom.vue')['default']
    PhoneSignalIcon: typeof import('./../components/iphone/PhoneSignalIcon.vue')['default']
    PhoneTopIcon: typeof import('./../components/iphone/PhoneTopIcon.vue')['default']
    PWAPrompt: typeof import('./../components/PWAPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./../components/common/SettingsModal.vue')['default']
    SettingsToolbar: typeof import('./../components/SettingsToolbar.vue')['default']
    ShareCard: typeof import('./../components/common/ShareCard.vue')['default']
    TabletFrame: typeof import('./../components/ipad/TabletFrame.vue')['default']
    TitleSettings: typeof import('./../components/toolbar/TitleSettings.vue')['default']
    WallpaperEditor: typeof import('./../components/WallpaperEditor.vue')['default']
    WatermarkSettings: typeof import('./../components/toolbar/WatermarkSettings.vue')['default']
  }
}
